version: "3.5"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
    networks:
      - main_proxy
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "/etc/localtime:/etc/localtime:ro"
        - "./configs/traefik/traefik.yml:/traefik.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"

  portainer:
    image: cr.portainer.io/portainer/portainer-ce:2.9.3
    container_name: "portainer"
    restart: always
    networks:
      - main_proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${MAIN_DOMAIN}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

#  teamcity:
#    restart: always
#    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
#    container_name: "server-cli"
#    volumes:
#      - './teamcity/teamcity_data:/data/teamcity_server/datadir'
#    networks:
#      - main_proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.server-cli.entrypoints=http"
#      - "traefik.http.routers.server-cli.rule=Host(`cli.${MAIN_DOMAIN}`)"
#      - "traefik.http.services.server-cli.loadbalancer.server.port=8111"
#
#  teamcity-agent:
#    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
#    privileged: true
#    restart: always
#    container_name: "teamcity-agent"
#    networks:
#      - main_proxy
#    volumes:
#      - './teamcity/teamcity_agents/agent:/data/teamcity_agent/conf'
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./:/home/buildagent/server_dir"
#    environment:
#      - DOCKER_IN_DOCKER=start
#      - SERVER_URL=server-cli:8111
#      - AGENT_NAME=${MAIN_DOMAIN}-teamcity-agent
#  proxy-database:
#    image: severalnines/proxysql:latest
#    container_name: proxy-database
#    restart: always
#    networks:
#      - main_proxy
#    ports:
#      - '6032:6032'
#      - '6033:6033'
#    volumes:
#      - "./configs/proxysql/proxysql.conf:/etc/proxysql.cnf"
#      - "./proxysql:/var/lib/proxysql"

networks:
  main_proxy:
    driver: bridge
    name: main_proxy