name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: 
        docker build ./httpd/ dengoose/httpd-php8
    - name: Docker push
      run:
        docker push dengoose/httpd-php8
